### ISSUE TITLE
Segfault when h2 and h2c are enabled

### ISSUE THREAD

**Issue by jaytaylor** [icing/mod_h2#165]
OS: Ubuntu 18.04
Apache2 version: 2.4.29-1ubuntu4.2

Greetings,

I'm trying to reverse-proxy a golang HTTP/2 + gRPC through apache2 via mod_http2.  With the apache2 configuration below, mod_h2 fails with a segfault for `curl https://example.com` and `curl --http2 https://example.com`, yet handles the gRPC endpoint requests through without issue.

The golang server is running http2 without TLS, so `h2c`.  Based on the coredump backtrace (included towards the end of this post), it's unclear to me whether or not a connection to the golang server is even being initiated for the cases that segfault.

```
<VirtualHost *:80>
    ServerName example.com
    ServerAlias example.com
    RedirectMatch permanent ^/(.*)$ https://example.com/$1
</VirtualHost>


<IfModule mod_ssl.c>
<VirtualHost _default_:443>
    ServerName example.com
    ServerAlias example.com

    Include conf.d/deflate.conf
    DeflateFilterNote ratio
    LogLevel info
    CustomLog /var/log/apache2/example.com-access_log deflate
    ErrorLog /var/log/apache2/example.com-error_log

    SSLCertificateFile /etc/letsencrypt/live/example.com/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateChainFile /etc/letsencrypt/live/example.com/chain.pem

    ModPagespeed on
    ModPagespeedEnableFilters insert_ga
    ModPagespeedAnalyticsID UA-XXX

    DocumentRoot /var/www/example.com/public_html

    <Directory /var/www/example.com/public_html>
        AllowOverride Indexes
        Options FollowSymLinks
        IndexOptions +FancyIndexing
        AllowOverride all
        Order allow,deny
        Allow from all
    </Directory>

    Protocols h2 h2c http/1.1

    ProxyPass / h2c://127.0.0.1:8001/
    ProxyPassReverse / hc2://127.0.0.1:8001/

</VirtualHost>
</IfModule>
```

While the gRPC workers are able to connect just fine, visiting `https://example.com` results in a segfault in the apache2 error log:

```
==> /var/log/apache2/error.log <==
[Mon Jul 09 16:56:00.928159 2018] [core:notice] [pid 30939:tid 139629403990976] AH00051: child pid 30943 exit signal Segmentation fault (11), possible coredump in /var/crash
```

If `h2` is removed from the list of the Protocols line like so:

```Protocols h2c http/1.1```

(which seems reasonable and like it _should_ theoretically work since the communication between apache2 and the proxied server are cleartext, the go server do not even speak TLS.)

Then:

* Segmentation faults stop occurring.
* Viewing the homepage still fails with a 503.
* gRPC workers are no longer able to connect.

I have the core dump files if they will help diagnose this.  Just let me know the address to drop them at if you want a few.

Here is a sample backtraces after installing the apache2 debug symbols package:

```
root@jaytaylor.com:/var/crash# gdb apache2 coredump-apache2.28495
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from apache2...Reading symbols from /usr/lib/debug/.build-id/e7/47257c2d6cc72a247343d8b9a9667134a3a3c7.debug...done.
done.
[New LWP 28564]
[New LWP 28554]
[New LWP 28520]
[New LWP 28516]
[New LWP 28542]
[New LWP 28556]
[New LWP 28619]
[New LWP 28517]
[New LWP 28620]
[New LWP 28548]
[New LWP 28560]
[New LWP 28513]
[New LWP 28538]
[New LWP 28495]
[New LWP 28582]
[New LWP 28507]
[New LWP 28563]
[New LWP 28558]
[New LWP 28613]
[New LWP 28536]
[New LWP 28540]
[New LWP 28621]
[New LWP 28569]
[New LWP 28567]
[New LWP 28566]
[New LWP 28618]
[New LWP 28534]
[New LWP 28579]
[New LWP 28561]
[New LWP 28611]
[New LWP 28602]
[New LWP 28559]
[New LWP 28565]
[New LWP 28599]
[New LWP 28532]
[New LWP 28623]
[New LWP 28608]
[New LWP 28546]
[New LWP 28568]
[New LWP 28562]
[New LWP 28577]
[New LWP 28584]
[New LWP 28606]
[New LWP 28622]
[New LWP 28544]
[New LWP 28510]
[New LWP 28597]
[New LWP 28586]
[New LWP 28512]
[New LWP 28552]
[New LWP 28595]
[New LWP 28550]
[New LWP 28522]
[New LWP 28581]
[New LWP 28593]
[New LWP 28590]
[New LWP 28524]
[New LWP 28588]
[New LWP 28526]
[New LWP 28615]
[New LWP 28604]
[New LWP 28528]
[New LWP 28530]
[New LWP 28624]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/apache2 -k start'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  h2_from_h1_parse_response (task=task@entry=0x7f11070c30a0, f=f@entry=0x7f11070c7750, bb=bb@entry=0x7f1107097f98) at h2_from_h1.c:481
481	h2_from_h1.c: No such file or directory.
[Current thread is 1 (Thread 0x7f10f6914700 (LWP 28564))]
(gdb) bt
#0  h2_from_h1_parse_response (task=task@entry=0x7f11070c30a0, f=f@entry=0x7f11070c7750, bb=bb@entry=0x7f1107097f98) at h2_from_h1.c:481
#1  0x00007f11171201cc in h2_filter_parse_h1 (f=0x7f11070c7750, bb=0x7f1107097f98) at h2_task.c:402
#2  0x00005574f53576fe in ap_http_header_filter (f=<optimized out>, b=0x7f1107097e98) at http_filters.c:1511
#3  0x00005574f5325921 in ap_content_length_filter (f=0x7f11070a25a8, b=0x7f1107097e98) at protocol.c:1792
#4  0x00005574f5359146 in ap_byterange_filter (f=0x7f11070a2580, bb=0x7f1107097e98) at byterange_filter.c:494
#5  0x00005574f5352df2 in ap_send_error_response (r=0x7f11070a10a0, recursive_error=0) at http_protocol.c:1554
#6  0x00005574f5354b4c in ap_process_async_request (r=0x7f11070a10a0) at http_request.c:459
#7  0x00005574f5354da0 in ap_process_request (r=r@entry=0x7f11070a10a0) at http_request.c:471
#8  0x00007f1117121406 in h2_task_process_request (c=0x7f11070c70a0, task=<optimized out>) at h2_task.c:677
#9  h2_task_process_conn (c=0x7f11070c70a0) at h2_task.c:724
#10 0x00005574f5346960 in ap_run_process_connection (c=c@entry=0x7f11070c70a0) at connection.c:42
#11 0x00007f111712280b in h2_task_do (task=0x7f11070c30a0, thread=thread@entry=0x7f110b8449c8, worker_id=<optimized out>) at h2_task.c:634
#12 0x00007f1117126276 in slot_run (thread=0x7f110b8449c8, wctx=0x7f111bb0a6a8) at h2_workers.c:230
#13 0x00007f111b09d6db in start_thread (arg=0x7f10f6914700) at pthread_create.c:463
#14 0x00007f111adc688f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

Overall I'm not sure what to make of all this, any assistance or insight into where things may be going wrong would be greatly appreciated!

Thank you,
J. Elliot Taylor

**Comment by icing** [comment]
Thanks for the detailed report. From the stack trace, I see that the segfault occurs while h2 is processing an error response (something like the 503 you see without h2). Looks clearly like a bug in my code.

Since this seems a security sensitive finding, I'd ask you to report this at security@httpd.apache.org with the content of this issue and then I clear and close the issue here. Ok?
